# Generated by Django 4.2.4 on 2023-08-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todosapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='id',
        ),
        migrations.AddField(
            model_name='todo',
            name='todos_id',
            field=models.IntegerField(auto_created=True, default=None, primary_key=True, serialize=False),
        ),
    ]
