# Generated by Django 4.2.4 on 2023-08-23 16:29

from django.db import migrations, models
from ..models import ToDo

class Migration(migrations.Migration):

    dependencies = [
        ('todosapp', '0002_remove_todo_id_todo_todos_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='duedate',
            field=models.DateTimeField(verbose_name='due date'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='startdate',
            field=models.DateTimeField(verbose_name='start date'),
        ),
        
    ]
